<?php

/**
 * clientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class clientTable extends sfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object clientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('client');
    }
}