<?php

/**
 * prestataireTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class prestataireTable extends sfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object prestataireTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('prestataire');
    }
}