<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/06/05 00:33:38

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=evento',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
